#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "wombat256mod"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    bootstrap_after = "myspacevim#after"
    relativenumber = false
    max_column = 120
    fill_column_visible = 1
    disabled_plugins = ['vim-startify']


[[layers]]
name = "colorscheme"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "debug"
debugger_plugin = "vimspector"

[[layers]]
name = "fzf"

[[layers]]
name = "sudo"

[[layers]]
name = "tmux"

[[layers]]
name = "checkers"

[[layers]]
name = "gtags"
gtagslabel = "ctags"

[[layers]]
name = "git"
git_plugin = "fugitive"

[[layers]]
name = "lang#python"
python_interpreter = "/usr/local/bin/python3"
enabled_linters = ["python", "pylint"]

[[layers]]
name = "lang#java"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#kotlin"

[[layers]]
name = "lang#rst"

[[layers]]
name = "lang#lisp"

[[layers]]
name = "lang#fennel"

#[[layers]]
#name = "lang#typescript"

[[layers]]
name = "lang#extra"

[[custom_plugins]]
repo = "junegunn/seoul256.vim"
merged = false

[[custom_plugins]]
repo = "bhurlow/vim-parinfer"
merged = false
